version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=m012015015
      - DB_NAME=Chinook
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: m012015015
      MYSQL_DATABASE: Chinook
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
