name: Vodafone Chatbot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install black isort bandit pytest coverage pylint pdoc3

    - name: Run code formatting
      run: |
        black src
        isort src

    - name: Run security checks
      continue-on-error: true
      run: bandit -r src -f custom

    - name: Run tests and coverage
      continue-on-error: true
      run: |
        cd src
        coverage run -m pytest
        coverage report

    - name: Generate documentation
      continue-on-error: true
      run: |
        cd src
        pdoc --html app.py test_app.py monitoring.py --output-dir ../documentation --force

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -m "Auto-commit: Applied formatting, updated docs" --allow-empty)

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/vodafone-chatbot:latest

    - name: Deploy to production
      run: |
        echo "Deploying to production server..."
        # Add your deployment commands here
